"""initial db schema

Revision ID: 974be4d3e686
Revises: 
Create Date: 2026-07-09 11:00:59.912910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '974be4d3e686'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'activity_logs', 'users', ['actor_id'], ['user_id'])
    op.create_foreign_key(None, 'debt_requests', 'users', ['lender_id'], ['user_id'])
    op.create_foreign_key(None, 'debt_requests', 'users', ['borrower_id'], ['user_id'])
    op.alter_column('debts', 'purpose',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_foreign_key(None, 'debts', 'users', ['lender_id'], ['user_id'])
    op.create_foreign_key(None, 'debts', 'users', ['borrower_id'], ['user_id'])
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['user_id'])
    op.alter_column('payments', 'notes',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_foreign_key(None, 'payments', 'users', ['created_by'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.alter_column('payments', 'notes',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'debts', type_='foreignkey')
    op.drop_constraint(None, 'debts', type_='foreignkey')
    op.alter_column('debts', 'purpose',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'debt_requests', type_='foreignkey')
    op.drop_constraint(None, 'debt_requests', type_='foreignkey')
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    # ### end Alembic commands ###
